# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""The relational schema: SQLAlchemy Core table metadata, no ORM.

Alembic autogenerates migrations by diffing against :data:`METADATA`, so this
file is the single source of truth for the schema — never hand-edit a migration
that has already been applied.

Four decisions shape everything downstream:

* **Containment is a parent foreign key, not an edge table.** A database owns
  its schemas, a schema its tables, a table its columns. That is what makes
  deleting a database one statement, with ``ON DELETE CASCADE`` doing the rest.
* **Ids are ``text`` uuids**, defaulted by ``gen_random_uuid()::text``. Not
  ``uuid``: every DAL signature is ``id: str``, and a malformed id arriving from
  a URL should yield an empty result rather than a ``22P02`` 500. Not integers:
  ids are consumed as opaque strings by the vector-store row key, the frontend's
  pipe-separated focus param, and ``model_interchange``'s ``imported_id OR id``
  match.
* **The catalog tier is prefixed ``catalog_``** — one rule that sidesteps
  ``table`` and ``column`` being reserved words and ``schema`` colliding with
  ``information_schema``, instead of three separate exceptions.
* **Association tables contain exactly one ``__``; entity tables contain none.**
  The name says which kind of table it is, and where the first endpoint's name
  ends. Both used to be guesswork: ``column_attribute_term`` could be read as
  ``column_attribute`` + ``term`` or ``column`` + ``attribute_term``, and
  nothing but familiarity separated it from the ``column_attribute`` entity
  sitting beside it.

  The separator marks the *first endpoint*, not a strict ``<source>__<target>``
  — which cannot name the self-edges (``column__join``, ``table__join``) or
  distinguish the two edges that share endpoints, ``column__has_attribute`` and
  ``column__semantic_fk``. Indexes and constraints follow their table's name, so
  ``pk_table__term`` never drifts back to the ambiguous form.
"""

from __future__ import annotations

from sqlalchemy import (
    ARRAY,
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Table,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB


#: The two terminal outcomes of a semantic compilation pass, for the check
#: constraint on :data:`semantic_compilation_history` below.
#:
#: Defined here rather than in ``gsf.ingestion_service.history``, which writes
#: them: they are part of the column's definition, and the module that writes
#: the values importing them from the constraint that permits them is the only
#: arrangement in which the two cannot disagree.
RUN_SUCCEEDED = "succeeded"
RUN_FAILED = "failed"

#: Naming convention so autogenerated constraints get stable, readable names.
#: Without it Alembic emits server-assigned names that differ between databases
#: and make a downgrade unable to find what it is dropping.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

# No ``schema=`` on purpose.
# Naming the default schema explicitly makes autogenerate emit permanent drift:
# metadata reports ``referent_schema='public'`` for every foreign key while
# reflection reports the default schema as ``None``, so Alembic sees 33 changed
# constraints and proposes dropping and recreating all of them, on every run,
# forever. Leaving it unset makes both sides agree. Placement is then decided by
# ``search_path``, which ``get_engine`` pins to ``public`` on every connection
# (see ``gsf/dal/session.py``) -- so it is guaranteed there, not here, and not
# by luck.
METADATA = MetaData(naming_convention=NAMING_CONVENTION)

#: ``gen_random_uuid()`` is built into Postgres from 13; no pgcrypto needed.
#:
#: Parenthesised to match how Postgres *stores* the expression. Written as
#: ``gen_random_uuid()::text`` it produces identical DDL, but the catalog reads
#: back ``(gen_random_uuid())::text``, and ``alembic check`` — which compares
#: server defaults as text — then reports drift on all 14 id columns on a
#: database that is perfectly up to date. Matching the normalised form keeps
#: the drift check meaningful instead of turning off ``compare_server_default``.
_UUID_DEFAULT = text("(gen_random_uuid())::text")


def _id() -> Column:
    return Column("id", Text, primary_key=True, server_default=_UUID_DEFAULT)


def _imported_id() -> Column:
    """Id carried over from a model-interchange export.

    ``_resolve_entities_batch`` matches YAML ids against ``imported_id OR id``,
    so an id from a previous export can arrive as an *imported* id on a node
    whose own id is different. Non-unique: two databases can legitimately import
    the same source model.
    """
    return Column("imported_id", Text, nullable=True)


def _certified(name: str) -> Column:
    """A human-set certification flag.

    ``NOT NULL DEFAULT false`` rather than nullable, because every read of these
    absent means false, and making that the column's job removes the coalesce
    from each caller — and, more usefully, the chance of one forgetting it.
    """
    return Column(name, Boolean, nullable=False, server_default=text("false"))


# ---------------------------------------------------------------------------
# Catalog tier — Database -> Schema -> Table -> Column
# ---------------------------------------------------------------------------

catalog_database = Table(
    "catalog_database",
    METADATA,
    _id(),
    Column("name", Text, nullable=False, unique=True),
    # UI-managed connection form. Stored here only when Vault is not configured;
    # with Vault the credentials live there and this stays null (the database
    # name is the lookup key -- there is no separate reference field).
    Column("connection", JSONB, nullable=True),
    Column("dialect", Text, nullable=True),
    # A database and a schema each carry a curated description, as tables and
    # columns do. Without them `patch_catalog_node` silently dropped the write
    # and still answered 200, so the UI reported success and the text was gone
    # on reload.
    Column("description", Text, nullable=True),
    _certified("description_certified"),
    _imported_id(),
    Column("created", DateTime(timezone=True), server_default=func.now()),
    Column("pulled", DateTime(timezone=True), nullable=True),
)

catalog_schema = Table(
    "catalog_schema",
    METADATA,
    _id(),
    Column(
        "database_id",
        Text,
        ForeignKey(catalog_database.c.id, ondelete="CASCADE"),
        nullable=False,
    ),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    _certified("description_certified"),
    _imported_id(),
    UniqueConstraint("database_id", "name", name="uq_catalog_schema_database_name"),
)


catalog_table = Table(
    "catalog_table",
    METADATA,
    _id(),
    Column(
        "schema_id",
        Text,
        ForeignKey(catalog_schema.c.id, ondelete="CASCADE"),
        nullable=False,
    ),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    # Set from the UI's certification checkbox, via patch_catalog_node. Easy to
    # miss, because nothing in the ingest ever writes it
    # -- it only appears once a human certifies a description. Without the
    # column the PATCH still returns 200 and the checkbox still ticks; the flag
    # is simply dropped on the way in and reads back false forever.
    _certified("description_certified"),
    # Primary key column names. A list on the node today, so a text[] here
    # rather than a join table -- nothing ever queries "which tables have this
    # pk column", and a join table would make every read a second query.
    Column("pk", ARRAY(Text), nullable=True),
    Column("table_type", Text, nullable=True),
    _imported_id(),
    UniqueConstraint("schema_id", "name", name="uq_catalog_table_schema_name"),
)

catalog_column = Table(
    "catalog_column",
    METADATA,
    _id(),
    Column(
        "table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        nullable=False,
    ),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    # As on catalog_table: written only by the UI's certification checkbox.
    _certified("description_certified"),
    Column("data_type", Text, nullable=True),
    # A JSON string, read back as a string by callers. Promoting it to jsonb is
    # a deliberate follow-up with its consumers updated, not a free change.
    Column("sample_values", Text, nullable=True),
    # How the values are *written*, not what they are: 'YYMMDD', 'YYYY-MM-DD'.
    # Generic storage notation despite only date inference filling it today
    # (`gsf.semantic.date_format`) -- an address or id profiler would write the
    # same field. `data_type`/`name`/`description` say what the values mean.
    #
    # It exists because date columns are held out of sample-value profiling, so
    # nothing else in the prompt tells the model what form to compare against:
    # `950324` and `1995-03-24` are the same day and share no predicate, and a
    # wrong guess yields SQL that runs, returns nothing, and looks right.
    Column("format", Text, nullable=True),
    Column("is_unique", Boolean, nullable=True),
    # A real Boolean. It used to hold the *strings* `information_schema`
    # reports, 'YES' and 'NO', which read back as truthy either way -- so
    # `bool(stored)` was True for every column and every export claimed the
    # whole catalog was nullable. Connectors now convert at their own edge
    # (see `gsf.connectors.base.SQLDatabase.get_columns`) and NULL still means
    # "the connector could not determine it", which callers treat as nullable.
    Column("is_nullable", Boolean, nullable=True),
    # A genuine integer, despite the parser handing the write path a string --
    # something coerces on the way in.
    Column("ordinal_position", Integer, nullable=True),
    _imported_id(),
    UniqueConstraint("table_id", "name", name="uq_catalog_column_table_name"),
)

# FOREIGN_KEY: Column -> Column.
column__foreign_key = Table(
    "column__foreign_key",
    METADATA,
    Column(
        "source_column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "target_column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    # Stamped by every ingest, then used to delete the keys this run did not
    # see -- the source database may have dropped a constraint. Without it
    # there is no way to tell a removed foreign key from one simply not
    # re-asserted, and stale keys would accumulate forever.
    Column("last_seen", DateTime(timezone=True), nullable=True),
)


# JOIN / UNION: Column <-> Column, carrying the statements that observed them.
#
# Distinct from `table__join` below, and both are real. This one is written by
# **query** ingestion -- `sql_parse` emits one entry per observed join
# condition, so `refs` accumulates `"<sql id>|<condition>"` strings as more
# statements are seen. `table__join` is written only by a model import and
# carries the join's *columns*; nothing writes both.
#
# `refs` is an array that grows rather than a row per reference, because that is
# what the readers expect. A row per ref would be the better model and is a deliberate follow-up,
# not a porting decision.
def _column_pair_edge(name: str) -> Table:
    return Table(
        name,
        METADATA,
        Column(
            "source_column_id",
            Text,
            ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
            primary_key=True,
        ),
        Column(
            "target_column_id",
            Text,
            ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
            primary_key=True,
        ),
        Column("refs", ARRAY(Text), nullable=False, server_default=text("'{}'")),
    )


column__join = _column_pair_edge("column__join")
column__union = _column_pair_edge("column__union")


# JOIN: Table -> Table, carrying the columns that join them.
table__join = Table(
    "table__join",
    METADATA,
    Column(
        "source_table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "target_table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("join_columns", JSONB, nullable=True),
)

# ---------------------------------------------------------------------------
# SQL statements and their table references
# ---------------------------------------------------------------------------

sql_query = Table(
    "sql_query",
    METADATA,
    _id(),
    Column("sql_full_query", Text, nullable=False),
    Column("query_count", Integer, nullable=False, server_default=text("0")),
    Column("created", DateTime(timezone=True), server_default=func.now()),
    Column("last_seen", DateTime(timezone=True), nullable=True),
    # How many times this statement has been observed, all time. The graph also
    # carried a `count_{month}_{year}` property per month, which is not
    # reproduced: no reader has ever been able to parse those names (they are
    # matched against `count_monthly_YYYY_MM`), so they hold no information
    # anything can use. See DECISIONS.md record 007.
    Column("total_counter", Integer, nullable=False, server_default=text("0")),
    Column("last_query_timestamp", DateTime(timezone=True), nullable=True),
    # Structural fingerprint, used to pre-filter candidates before the
    # expensive sqlglot comparison in query deduplication.
    Column("nodes_count", Integer, nullable=True),
    Column("join_count", Integer, nullable=False, server_default=text("0")),
    Column("union_count", Integer, nullable=False, server_default=text("0")),
    # model_interchange matches a Sql node by its *text*
    # (match_props={"sql_full_query": sql}). Statement text can exceed the btree
    # row limit, so the uniqueness is enforced on a hash rather than the column.
    Index(
        "uq_sql_query_text_md5",
        func.md5(text("sql_full_query")),
        unique=True,
    ),
)

# SQL: Sql -> Table. An association, because one statement references many
# tables and one table is referenced by many statements.
sql_query__table = Table(
    "sql_query__table",
    METADATA,
    Column(
        "sql_query_id",
        Text,
        ForeignKey(sql_query.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

# SQL: Sql -> Column. The same relationship type, pointing at the leaf columns a
# statement selects. Two tables rather than one polymorphic association, because
# the two are always read separately -- `load_sqls_to_tables` returns tables and
# columns as distinct lists, and query deduplication compares them as distinct
# sets.
sql_query__column = Table(
    "sql_query__column",
    METADATA,
    Column(
        "sql_query_id",
        Text,
        ForeignKey(sql_query.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

# ---------------------------------------------------------------------------
# Semantic tier
# ---------------------------------------------------------------------------

term = Table(
    "term",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("source", Text, nullable=False, server_default=text("'semantic'")),
    Column("synonyms", ARRAY(Text), nullable=True),
    _certified("name_certified"),
    _certified("description_certified"),
    _imported_id(),
    UniqueConstraint("name", "source", name="uq_term_name_source"),
)

# REPRESENTS: Table -> Term.
table__term = Table(
    "table__term",
    METADATA,
    Column(
        "table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "term_id", Text, ForeignKey(term.c.id, ondelete="CASCADE"), primary_key=True
    ),
)

column_attribute = Table(
    "column_attribute",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("datatype", Text, nullable=True),
    Column("source", Text, nullable=False, server_default=text("'semantic'")),
    Column("source_column", Text, nullable=False),
    Column("term_name", Text, nullable=False),
    # Deliberately NOT a foreign key, and deliberately not nullable. The
    # importer legitimately writes '' when col_ctx is missing
    # (model_interchange.py:1260), and this is compared as a plain string in
    # `ca.table_id IN $table_ids`. An FK here would reject valid imports.
    Column("table_id", Text, nullable=False),
    Column("certified", Boolean, nullable=False, server_default=text("false")),
    Column("description_suggestion", Text, nullable=True),
    _imported_id(),
    # The 5-part merge key, exactly as merge_column_attribute matches on.
    UniqueConstraint(
        "name",
        "source_column",
        "term_name",
        "table_id",
        "source",
        name="uq_column_attribute_merge_key",
    ),
)

# PROPERTY_OF: ColumnAttribute -> Term.
#
# An edge table for what is really a one-to-many: the composite primary key only
# forbids the same pair twice, so it is `UNIQUE(attribute_id)` below that holds
# the rule the readers rely on -- **one Term per attribute**. Before it, the rule
# lived only in `link_to_term`, which deletes any other link before inserting,
# and every read that resolved an attribute's Term had to defend against a write
# path that forgot to.
column_attribute__term = Table(
    "column_attribute__term",
    METADATA,
    Column(
        "attribute_id",
        Text,
        ForeignKey(column_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "term_id", Text, ForeignKey(term.c.id, ondelete="CASCADE"), primary_key=True
    ),
    UniqueConstraint("attribute_id"),
)

# HAS_ATTRIBUTE and SEMANTIC_FK both run Column -> ColumnAttribute, but they
# assert different things and get their own tables rather than one table with a
# `kind` discriminator:
#
#   HAS_ATTRIBUTE  this column *is* an instance of the attribute
#   SEMANTIC_FK    this column *references* the attribute, which describes a
#                  column on another table
#
# Their cardinality already differs -- `resolve_semantic_fks` treats a column as
# unlinked when it has no SEMANTIC_FK, so at most one is expected, whereas a
# column can carry several attributes -- and a discriminator in the primary key
# makes any constraint that applies to only one of them impossible to express.
column__has_attribute = Table(
    "column__has_attribute",
    METADATA,
    Column(
        "column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "attribute_id",
        Text,
        ForeignKey(column_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

column__semantic_fk = Table(
    "column__semantic_fk",
    METADATA,
    Column(
        "column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "attribute_id",
        Text,
        ForeignKey(column_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

sql_attribute = Table(
    "sql_attribute",
    METADATA,
    _id(),
    Column("name", Text, nullable=False, unique=True),
    Column("description", Text, nullable=True),
    Column("expression", Text, nullable=True),
    Column("source", Text, nullable=True),
    Column("certified", Boolean, nullable=False, server_default=text("false")),
    Column("description_suggestion", Text, nullable=True),
    _imported_id(),
    CheckConstraint(
        "source IS NULL OR source IN ('manual', 'sql', 'table', 'bridgeTable')",
        name="source_value",
    ),
)

# PROPERTY_OF: SqlAttribute -> Term.
#
# `UNIQUE(attribute_id)` for the reason given on `column_attribute__term`: the
# two kinds of attribute are properties of exactly one Term in the same sense,
# and the pages that list them read both the same way. A SqlAttribute reached
# through a CustomAnalysis has no row here at all, which is a different thing
# from having two.
sql_attribute__term = Table(
    "sql_attribute__term",
    METADATA,
    Column(
        "attribute_id",
        Text,
        ForeignKey(sql_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "term_id", Text, ForeignKey(term.c.id, ondelete="CASCADE"), primary_key=True
    ),
    UniqueConstraint("attribute_id"),
)

# HAS_SQL: SqlAttribute -> Sql.
sql_attribute__sql = Table(
    "sql_attribute__sql",
    METADATA,
    Column(
        "attribute_id",
        Text,
        ForeignKey(sql_attribute.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "sql_query_id",
        Text,
        ForeignKey(sql_query.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

custom_analysis = Table(
    "custom_analysis",
    METADATA,
    _id(),
    Column("name", Text, nullable=False, unique=True),
    Column("description", Text, nullable=True),
    _imported_id(),
)

# HAS_SQL: CustomAnalysis -> Sql.
custom_analysis__sql = Table(
    "custom_analysis__sql",
    METADATA,
    Column(
        "analysis_id",
        Text,
        ForeignKey(custom_analysis.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "sql_query_id",
        Text,
        ForeignKey(sql_query.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
)

pql_analysis = Table(
    "pql_analysis",
    METADATA,
    _id(),
    # Predictive few-shots must stay inside the graph/database they were
    # reviewed against. Legacy rows are nullable until they are re-imported;
    # scoped retrieval deliberately ignores those unowned examples.
    Column("database_name", Text, nullable=True, index=True),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("pql", Text, nullable=True),
    _imported_id(),
)

# Declared in gsf/semantic/constants.py and referenced by reset.py's
# _SEMANTIC_LABELS, but never written by GSF today. Created so the reset
# cascade has something to point at and so a future writer needs no migration.
text_attribute = Table(
    "text_attribute",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    _imported_id(),
)

analysis = Table(
    "analysis",
    METADATA,
    _id(),
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    _imported_id(),
)

# ---------------------------------------------------------------------------
# Zones
# ---------------------------------------------------------------------------

zone = Table(
    "zone",
    METADATA,
    _id(),
    # Deliberately **not** unique. The rule the application enforces is neither
    # what a plain UNIQUE gives you nor a stricter version of it:
    #
    #   * it is case-insensitive on the *trimmed* name, so a UNIQUE column would
    #     admit "Sales" alongside "sales", which the application rejects; and
    #   * it is scoped to zones sharing a database with the zone's items, so a
    #     UNIQUE column would reject the same zone name in two unrelated
    #     databases, which the application allows.
    #
    # A constraint that is wrong in both directions is worse than none. The
    # check stays in application code, exactly as today. Making it a database
    # constraint would mean a partial index on `lower(trim(name))` *per
    # database*, which zone membership -- being many-to-many through
    # zone_target -- cannot express.
    Column("name", Text, nullable=False),
    Column("description", Text, nullable=True),
    Column("color", Text, nullable=True),
    # A disabled zone still exists and is still administrable; it just grants
    # nothing. A boolean rather than a separate table so every read says
    # `enabled` once instead of unioning two sources.
    Column("enabled", Boolean, nullable=False, server_default=text("true")),
)

# ZONE_OF is polymorphic: a zone can target a Database, a Schema or a Table.
# Three nullable FKs with a CHECK beats a (kind, id) pair because it keeps real
# referential integrity and lets a deleted table remove its zone membership by
# cascade -- a (kind, id) pair cannot have an FK at all, and would leave
# dangling grants behind, which is an access-control bug rather than untidiness.
zone_target = Table(
    "zone_target",
    METADATA,
    _id(),
    Column("zone_id", Text, ForeignKey(zone.c.id, ondelete="CASCADE"), nullable=False),
    Column(
        "database_id",
        Text,
        ForeignKey(catalog_database.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    Column(
        "schema_id",
        Text,
        ForeignKey(catalog_schema.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    Column(
        "table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    CheckConstraint(
        "num_nonnulls(database_id, schema_id, table_id) = 1",
        name="exactly_one_target",
    ),
)

# ---------------------------------------------------------------------------
# Tags
# ---------------------------------------------------------------------------

tag = Table(
    "tag",
    METADATA,
    _id(),
    # Uniqueness is `uq_tag_name_lower`, not a UNIQUE on this column: the rule
    # the application enforces is case-insensitive on the *trimmed* name, and a
    # plain UNIQUE would admit "PII" beside "pii".
    Column("name", Text, nullable=False),
    Column(
        "created",
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    ),
    # Set by the database on insert and by SQLAlchemy's ``onupdate`` on every
    # UPDATE the DAL issues, so no caller has to remember to touch it -- a
    # rename advances it without `update_tag` naming this column at all. Equal
    # to ``created`` until a tag is first renamed, which is why the settings
    # page renders it as "Never" rather than repeating the creation date as if
    # the tag had been changed.
    Column(
        "modified",
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    ),
    # Who created the tag and who last edited it, as Better Auth user ids --
    # the `id` of a row in `frontend."user"`, which Prisma owns.
    #
    # Deliberately not foreign keys. That table is in another schema Alembic
    # does not manage, so there is nothing here to reference; and a tag must
    # outlive the account that made it, which a FK with any `ondelete` would
    # either forbid or quietly rewrite.
    #
    # Nullable because the gateway's identity header is not guaranteed: FastAPI
    # is reachable directly on the private network, so a caller that skips the
    # gateway creates a tag with nobody to record. The settings page reads that
    # as "Auto Generated" -- with no account to name, the deployment is what is
    # left -- rather than inventing an author.
    #
    # `modified_by` is additionally null for a tag nothing has edited yet, which
    # is the same fact `modified == created` states -- the page renders those
    # two together as an edit that never happened.
    #
    # Either may also hold an id no account answers to, since these are not
    # foreign keys and an account can be deleted; the page reads that the same
    # way it reads a null, having nobody to name either way.
    Column("created_by", Text, nullable=True),
    Column("modified_by", Text, nullable=True),
    # The tag name rule as a constraint rather than a convention. Unlike
    # `zone.name` -- whose rule is scoped to the databases a zone's items live
    # in, which no index can express -- a tag name is unique across the whole
    # deployment, so an expression index states the rule exactly. It also closes
    # the window between the DAL's duplicate check and its insert, which two
    # concurrent creates of the same name would otherwise slip through.
    #
    # Spelled as `text()` in Postgres's own deparsed form, and declared here
    # rather than beside the other indexes below, for two reasons `alembic
    # check` fails on otherwise: `func.lower(func.trim(...))` renders
    # `lower(trim(name))` while reflection reports `lower(TRIM(BOTH FROM
    # name))`, and a bare `text()` index outside a Table is attached to no
    # table, so autogenerate reads it as an index the models no longer have.
    Index("uq_tag_name_lower", text("lower(TRIM(BOTH FROM name))"), unique=True),
)

# TAGGED is polymorphic: a tag can label a Term, a Table, a Column, a
# ColumnAttribute or a SqlAttribute. Same nullable-FKs-and-a-CHECK shape as
# `zone_target`, and for the same reason -- a (kind, id) pair can carry no
# foreign key, so deleting a column would leave a row pointing at nothing and
# the tag's page would list objects that no longer exist. Here the cascade
# removes the label with the thing it labelled.
#
# Databases and Schemas are deliberately absent. A tag is applied to the objects
# a query names, and the two container tiers already reach their contents
# through `zone_target`, which is what scopes access.
tag_target = Table(
    "tag_target",
    METADATA,
    _id(),
    Column("tag_id", Text, ForeignKey(tag.c.id, ondelete="CASCADE"), nullable=False),
    Column(
        "term_id",
        Text,
        ForeignKey(term.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    Column(
        "table_id",
        Text,
        ForeignKey(catalog_table.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    Column(
        "column_id",
        Text,
        ForeignKey(catalog_column.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    Column(
        "column_attribute_id",
        Text,
        ForeignKey(column_attribute.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    Column(
        "sql_attribute_id",
        Text,
        ForeignKey(sql_attribute.c.id, ondelete="CASCADE"),
        nullable=True,
    ),
    # When the label was applied, for the "Tagged" column on the tag's page.
    Column(
        "tagged",
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    ),
    # Who applied it, for the "Tagged By" column beside it. A Better Auth user
    # id from the gateway's identity header, and not a foreign key: the accounts
    # live in the `frontend` schema Prisma owns, which this database has no
    # table for -- the same arrangement as `tag.created_by`.
    #
    # Null for a label a rule applied, where `rule_id` names the source
    # instead; for one the deployment applied itself, which is what an attach
    # carrying no identity records; and for a row written before this column
    # existed. The page reads the last two the same way, as "Auto Generated" --
    # with no account and no rule claiming a label, the deployment is what is
    # left, and an older row is a label nobody ever claimed either.
    Column("tagged_by", Text, nullable=True),
    # The rule that applied it, when a rule did rather than a person. Null for a
    # hand-applied label, and the two are exclusive: `tagged_by` is the account
    # that clicked, `rule_id` the rule that matched.
    #
    # `ON DELETE CASCADE`, so deleting a rule takes back what it labelled. A
    # rule-applied tag is the rule still holding, not a fact of its own -- it is
    # re-applied as the catalog grows, and would otherwise outlive the only
    # thing that could explain it.
    #
    # A caller who wants the labels to outlive the rule anyway says so, and
    # `rules.delete_rule` clears this column before deleting -- writing the
    # rule's author into `tagged_by` as it goes, so the label reads as that
    # person's rather than as nobody's -- and the cascade then has nothing of
    # the rule's to take. That is a decision at the call site rather than a
    # weaker constraint here: while a rule exists, a label naming it is the
    # rule's.
    #
    # A one-per-(tag, object) row, so a rule cannot re-label what a person
    # already labelled by hand, or the other way about: whichever came first
    # keeps the row, and the unique constraints below absorb the second write.
    #
    # The target is named as a string because `rule` is declared further down
    # this module -- the tables read in tag order, and a rule is a later idea
    # than a tag.
    Column(
        "rule_id",
        Text,
        ForeignKey("rule.id", ondelete="CASCADE"),
        nullable=True,
    ),
    CheckConstraint(
        "num_nonnulls(term_id, table_id, column_id, column_attribute_id, "
        "sql_attribute_id) = 1",
        name="exactly_one_target",
    ),
    # One row per (tag, object), as one constraint per target column rather than
    # one across all of them. That works *because* Postgres treats NULLs as
    # distinct: the columns that do not apply to a row are null, so those
    # constraints never collide, while the one that does is enforced. A single
    # UNIQUE over every column would enforce nothing at all, for the same reason.
    #
    # Each also gives a btree led by `tag_id`, which is the read behind a tag's
    # page -- "the objects carrying this tag" -- so no separate index on `tag_id`
    # is needed. The reverse read, "the tags on this object", leads with the
    # target column instead and is served by the indexes declared below.
    UniqueConstraint("tag_id", "term_id", name="uq_tag_target_tag_id_term_id"),
    UniqueConstraint("tag_id", "table_id", name="uq_tag_target_tag_id_table_id"),
    UniqueConstraint("tag_id", "column_id", name="uq_tag_target_tag_id_column_id"),
    UniqueConstraint(
        "tag_id",
        "column_attribute_id",
        name="uq_tag_target_tag_id_column_attribute_id",
    ),
    UniqueConstraint(
        "tag_id", "sql_attribute_id", name="uq_tag_target_tag_id_sql_attribute_id"
    ),
)

# ---------------------------------------------------------------------------
# Rules
# ---------------------------------------------------------------------------

# A rule is a saved global search plus the tags to apply to everything it
# matches. The three search columns are what the rule *replays*, so they are
# spelled the way `/search/global-search` takes the request rather than
# decomposed further -- a rule that cannot be handed back to the search is a
# rule that never reproduces what it was created from.
rule = Table(
    "rule",
    METADATA,
    _id(),
    # Uniqueness is `uq_rule_name_lower`, below, as a tag's is: the name is how
    # the settings list refers to a rule, so two rules answering to one name
    # leave a reader unable to say which one they are about to delete -- and a
    # delete takes back everything that rule labelled.
    Column("name", Text, nullable=False),
    Column("search_term", Text, nullable=False),
    # `contains` is the only match global search implements today, so the
    # default is the whole vocabulary. Deliberately no CHECK constraint pinning
    # it: the permitted set belongs to the search, which validates it in
    # `gsf/server/rules/router.py`, and a constraint here would make adding a
    # match option a schema migration.
    Column(
        "text_match_option", Text, nullable=False, server_default=text("'contains'")
    ),
    # The search filters, stored whole. JSONB rather than a column each because
    # this is one value that travels together -- it is written by the create and
    # read back to be handed to the search, never filtered or joined on -- and
    # because `GlobalSearchFilters` gains fields as the search does, which would
    # otherwise be a migration per flag.
    #
    # Only the filters a caller sent land here: the route dumps them with
    # `exclude_none`, so a rule saved from the search's All tab has no `objects`
    # key rather than a null one. A read fills the defaults back in, so the API
    # answers the same shape either way.
    Column("filters", JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    Column(
        "created",
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    ),
    # Advanced by `onupdate` on every UPDATE the DAL issues, as `tag.modified`
    # is, so it is the last edit rather than the last one somebody remembered to
    # record.
    Column(
        "modified",
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    ),
    # NOT NULL, unlike `tag.created_by`, and not a foreign key for the same
    # reasons that column is not: the accounts live in a schema Alembic does not
    # manage, and a rule must outlive the account that saved it.
    #
    # Required because the route refuses a create it cannot attribute -- a rule
    # goes on labelling the catalog long after it was saved, so "nobody" is not
    # an author it may record.
    Column("created_by", Text, nullable=False),
    # Who last renamed the rule, as `tag.modified_by` records for a tag.
    #
    # Nullable, unlike `created_by`, and for a reason `created_by` cannot have:
    # a rule that nobody has edited has no editor, which is the same fact as
    # `modified == created`. It is set on every rename, including one carrying
    # no identity -- leaving the previous editor would credit this edit to them.
    Column("modified_by", Text, nullable=True),
    # Case- and whitespace-insensitive uniqueness on the name, spelled exactly
    # as `uq_tag_name_lower` is and for the reasons given there: an expression
    # index states the rule the DAL checks, and closes the window between that
    # check and the write which two concurrent creates would slip through.
    Index("uq_rule_name_lower", text("lower(TRIM(BOTH FROM name))"), unique=True),
)

# The tags a rule applies. A link table rather than a list on `rule` so a tag
# deleted from the vocabulary leaves the rules that used it by cascade, instead
# of leaving them applying an id that no longer names anything.
rule__tag = Table(
    "rule__tag",
    METADATA,
    Column(
        "rule_id",
        Text,
        ForeignKey(rule.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "tag_id",
        Text,
        ForeignKey(tag.c.id, ondelete="CASCADE"),
        primary_key=True,
    ),
    # The order the tags were picked in, so a rule reads back as it was written.
    # The composite primary key orders by id, which is not that.
    #
    # The id and the position are the whole of what this table has to say. A
    # tag's own columns are the `tag` table's, read through the foreign key on
    # every read, so a renamed tag reads back renamed here and no copy of it
    # can go stale beside the original.
    Column("position", Integer, nullable=False),
)

# ---------------------------------------------------------------------------
# Service bookkeeping
# ---------------------------------------------------------------------------

# One row per semantic compilation pass, written by the ingestion service (see
# `gsf.ingestion_service.history`) and read back by the settings page.
#
# It arrived creating itself at service startup instead of through a migration.
# That is why it is worth a note: a `public` table this schema does not declare
# is indistinguishable from one deleted from the model, so autogenerate emitted
# `drop_table` for it on every run -- exactly what `include_object` in
# `alembic/env.py` warns a stray table invites.
semantic_compilation_history = Table(
    "semantic_compilation_history",
    METADATA,
    # BIGSERIAL, unlike the Text uuids everywhere else here: rows are appended
    # in time order by one writer and read back "most recent first", which an
    # ascending integer answers directly.
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("started_at", DateTime(timezone=True), nullable=False),
    # NULL until the pass reaches a terminal outcome -- which it never does if
    # it was stopped, disabled mid-run, or killed. See `history.py` on why an
    # unfinished pass is left this way rather than given an "aborted" status.
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("status", Text, nullable=True),
    CheckConstraint(
        f"status IS NULL OR status IN ('{RUN_SUCCEEDED}', '{RUN_FAILED}')",
        name="status_value",
    ),
)


# ---------------------------------------------------------------------------
# Indexes for the read paths
# ---------------------------------------------------------------------------

Index("ix_catalog_schema_database_id", catalog_schema.c.database_id)
Index("ix_catalog_table_schema_id", catalog_table.c.schema_id)
Index("ix_catalog_table_name", catalog_table.c.name)
Index("ix_catalog_column_table_id", catalog_column.c.table_id)
Index("ix_catalog_column_name", catalog_column.c.name)

Index("ix_column__foreign_key_target", column__foreign_key.c.target_column_id)
Index("ix_table__join_target", table__join.c.target_table_id)
Index("ix_sql_query__table_table_id", sql_query__table.c.table_id)
Index("ix_sql_query__column_column_id", sql_query__column.c.column_id)

Index("ix_term_name", term.c.name)
Index("ix_table__term_term_id", table__term.c.term_id)
Index("ix_column_attribute_term_name", column_attribute.c.term_name)
Index("ix_column_attribute_table_id", column_attribute.c.table_id)
Index("ix_column_attribute__term_term_id", column_attribute__term.c.term_id)
Index("ix_sql_attribute__term_term_id", sql_attribute__term.c.term_id)

# Both link tables are read in both directions -- from a column to its
# attributes, and from an attribute back to the columns that reference it
# (`fetch_attr_column_contexts` binds the attribute first). The composite
# primary key already indexes the column_id order; these cover the reverse.
Index("ix_column__has_attribute_attribute_id", column__has_attribute.c.attribute_id)
Index("ix_column__semantic_fk_attribute_id", column__semantic_fk.c.attribute_id)

# Supports the case-insensitive name check that replaces a unique constraint.
Index("ix_zone_name_lower", func.lower(zone.c.name))
Index("ix_zone_target_zone_id", zone_target.c.zone_id)
Index("ix_zone_target_database_id", zone_target.c.database_id)
Index("ix_zone_target_schema_id", zone_target.c.schema_id)
Index("ix_zone_target_table_id", zone_target.c.table_id)

# "The tags on this object", which every detail page asks for its own kind. The
# unique constraints on tag_target lead with `tag_id` and so cannot serve it.
Index("ix_tag_target_term_id", tag_target.c.term_id)
Index("ix_tag_target_table_id", tag_target.c.table_id)
Index("ix_tag_target_column_id", tag_target.c.column_id)
Index("ix_tag_target_column_attribute_id", tag_target.c.column_attribute_id)
Index("ix_tag_target_sql_attribute_id", tag_target.c.sql_attribute_id)

# The order the Rules settings page renders in, and the reverse read the
# cascade needs: `rule__tag`'s primary key leads with `rule_id`, so deleting a
# tag would scan the whole table for the rules that carry it without this.
Index("ix_rule_name_lower", func.lower(rule.c.name))
Index("ix_rule__tag_tag_id", rule__tag.c.tag_id)

# The other side of that cascade: deleting a rule takes back every label it
# applied, and nothing else leads with `tag_target.rule_id`.
Index("ix_tag_target_rule_id", tag_target.c.rule_id)

# imported_id is matched alongside id during model import; non-unique.
for _table in (
    catalog_database,
    catalog_schema,
    catalog_table,
    catalog_column,
    term,
    column_attribute,
    sql_attribute,
    custom_analysis,
):
    Index(f"ix_{_table.name}_imported_id", _table.c.imported_id)

# ---------------------------------------------------------------------------
# Trigram indexes for global search
# ---------------------------------------------------------------------------

#: Every table global search reads, and so every table that needs the indexes
#: below. ``View`` is absent because it is not a table of its own -- it is
#: ``catalog_table`` filtered by ``table_type``. ``gsf.dal.search`` maps labels
#: onto these, and a test there asserts the two sets have not drifted apart.
TRIGRAM_SEARCH_TABLES = (
    catalog_database,
    catalog_schema,
    catalog_table,
    catalog_column,
    custom_analysis,
    term,
    column_attribute,
    sql_attribute,
    pql_analysis,
)

#: Global search matches a *substring*: typing ``mount`` has to find
#: ``total_amount``. Nothing else indexes that. A btree needs a left anchor, so
#: it cannot serve an unanchored ``LIKE`` at all, and ``tsvector`` reaches only
#: the front of a token -- ``to_tsquery('mount:*')`` misses the word it sits
#: inside. ``pg_trgm`` indexes a string's three-character sequences, which is
#: what makes ``ILIKE '%mount%'`` indexable rather than a sequential scan of
#: every catalog row on every keystroke.
#:
#: Both columns are indexed because a search matches either one, ``description``
#: only when the caller asks for it. Neither carries ``lower()``: ``gin_trgm_ops``
#: folds case itself, so ``ILIKE`` uses these exactly as written -- adding
#: ``lower()`` here would build an index that ``ILIKE`` then could not match.
for _table in TRIGRAM_SEARCH_TABLES:
    for _column in ("name", "description"):
        Index(
            f"ix_{_table.name}_{_column}_trgm",
            _table.c[_column],
            postgresql_using="gin",
            postgresql_ops={_column: "gin_trgm_ops"},
        )

# ---------------------------------------------------------------------------
# join_path_edge view -- no longer read from Python; see note below.
# ---------------------------------------------------------------------------

#: Was the edge set for :func:`gsf.dal.attributes.find_join_path` and
#: :func:`gsf.dal.attributes.find_table_bridge`; both now traverse
#: ``_find_table_join_hops`` instead, which reads ``column__semantic_fk`` and
#: ``column__has_attribute`` directly rather than through this view. Nothing
#: in ``gsf/dal/attributes.py`` queries this view anymore -- it's kept
#: (unused) rather than dropped here, since removing it is a migration
#: decision, not a side effect of a traversal change. Its original shape,
#: kept for that future cleanup:
#:
#: * ``CONTAINS`` (Table <-> Column) and ``HAS_ATTRIBUTE``
#:   (Column <-> ColumnAttribute) appear in both directions.
#: * ``SEMANTIC_FK`` appears **outgoing only** (Column -> ColumnAttribute).
#:
#: Note carefully what that last line does *not* say. ``SEMANTIC_FK`` is
#: **stored** in one direction, but the codebase reads it in both:
#: ``fetch_attr_column_contexts`` binds a ColumnAttribute and finds the columns
#: referencing it, which is the reverse traversal. Anything needing that must
#: query :data:`column__semantic_fk` directly rather than this view.
#:
#: The restriction is specific to path-finding. Allowed to traverse SEMANTIC_FK
#: backwards, a path would hop from one FK column up to a shared target
#: attribute and back down a *different* FK column, inventing a join between two
#: columns that merely reference the same thing -- two ``customer_id`` columns
#: joined to each other. Here that is simply a row the view does not emit.
JOIN_PATH_EDGE_VIEW_SQL = """
CREATE OR REPLACE VIEW join_path_edge AS
    SELECT 'column'::text AS src_kind, c.id       AS src_id,
           'table'::text  AS dst_kind, c.table_id AS dst_id
      FROM catalog_column c
    UNION ALL
    SELECT 'table', c.table_id, 'column', c.id
      FROM catalog_column c
    UNION ALL
    SELECT 'column', h.column_id, 'column_attribute', h.attribute_id
      FROM column__has_attribute h
    UNION ALL
    SELECT 'column_attribute', h.attribute_id, 'column', h.column_id
      FROM column__has_attribute h
    UNION ALL
    SELECT 'column', f.column_id, 'column_attribute', f.attribute_id
      FROM column__semantic_fk f
"""

DROP_JOIN_PATH_EDGE_VIEW_SQL = "DROP VIEW IF EXISTS join_path_edge"

#: The view as something ``select()`` can take, on its **own** ``MetaData``.
#:
#: Not on :data:`METADATA`, deliberately. Alembic autogenerates by diffing that
#: object against the database and cannot tell a view from a table, so a view
#: registered there would be emitted as a ``CREATE TABLE`` on the next
#: autogenerate and then reported as permanent drift. Keeping it in a separate
#: registry means the DDL above stays the single definition of this view, while
#: queries still get column objects instead of raw strings.
VIEWS = MetaData()  # unqualified, for the same reason as METADATA

join_path_edge = Table(
    "join_path_edge",
    VIEWS,
    Column("src_kind", Text, nullable=False),
    Column("src_id", Text, nullable=False),
    Column("dst_kind", Text, nullable=False),
    Column("dst_id", Text, nullable=False),
)

__all__ = [
    "METADATA",
    "TRIGRAM_SEARCH_TABLES",
    "column__join",
    "column__union",
    "VIEWS",
    "join_path_edge",
    "JOIN_PATH_EDGE_VIEW_SQL",
    "DROP_JOIN_PATH_EDGE_VIEW_SQL",
    "analysis",
    "catalog_column",
    "catalog_database",
    "catalog_schema",
    "catalog_table",
    "column_attribute",
    "column__has_attribute",
    "column__semantic_fk",
    "column_attribute__term",
    "column__foreign_key",
    "custom_analysis",
    "custom_analysis__sql",
    "pql_analysis",
    "sql_attribute",
    "sql_attribute__sql",
    "sql_attribute__term",
    "sql_query",
    "sql_query__table",
    "sql_query__column",
    "semantic_compilation_history",
    "table__join",
    "table__term",
    "term",
    "text_attribute",
    "zone",
    "zone_target",
]
